// examples/solidstart-subdomain/src/entry-server.tsx
import { createHandler, StartServer } from "@solidjs/start/server"

export default createHandler(() => (
  <StartServer
    document={({ assets, children, scripts }) => (
      <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          {assets}
        </head>
        <body>
          <div id="app">{children}</div>
          {scripts}
        </body>
      </html>
    )}
  />
))

// examples/solidstart-tld/src/entry-server.tsx
import { createHandler, StartServer } from "@solidjs/start/server"
import { getRequestEvent } from "solid-js/web"
import { resolveHostLocale } from "./lib/server"

export default createHandler(() => (
  <StartServer
    document={({ assets, children, scripts }) => {
      const { locale } = resolveHostLocale(getRequestEvent()?.request)

      return (
        <html lang={locale}>
          <head>
            <meta charset="utf-8" />
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            {assets}
          </head>
          <body>
            <div id="app">{children}</div>
            {scripts}
          </body>
        </html>
      )
    }}
  />
))
