// examples/nextjs-route/src/app/[locale]/page.tsx
import { t } from "@palamedes/core/macro";
import { EVENT } from "@palamedes/example-ui";
import { ClientReady } from "@/components/ClientReady";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { ProofPanel } from "@/components/ProofPanel";
import { SuggestionBanner } from "@/components/SuggestionBanner";
import { TicketPanel } from "@/components/TicketPanel";
import { createActiveServerI18n, getRouteLocale, runWithServerI18n } from "@/lib/i18n.server";
import { getLocaleLabel, type Locale } from "@/lib/i18n";

// These functions run only inside `runWithServerI18n()`'s request-local scope.
function translateEyebrow(): string {
  return t`Localized for this document with Palamedes`;
}

function translateHeadline(): string {
  return t`Book your seat at Frontend Stage 2026`;
}

function translateGreeting(attendeeName: string): string {
  return t`Welcome back, ${attendeeName}.`;
}

function translateLede(): string {
  return t`Three days of talks on the craft of building for the web. Choose your tickets below.`;
}

function translateRenderedWith(): string {
  return t`Rendered with Next.js`;
}

function translateServerLocale(): string {
  return t`server locale`;
}

function translateSwitchToRecommended(): string {
  return t`Switch to the recommended locale`;
}

export default async function RouteHome({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  const { banner, locale } = await getRouteLocale(rawLocale);
  const { i18n } = await createActiveServerI18n(locale as Locale);
  const localeLabel = getLocaleLabel(locale);

  return runWithServerI18n(i18n, () => (
    <main className="page-shell">
      {banner ? (
        <SuggestionBanner
          ctaLabel={translateSwitchToRecommended()}
          currentLocale={locale}
          description={banner.description}
          recommendedLocale={banner.recommendedLocale}
          recommendedUrl={banner.recommendedUrl}
        />
      ) : null}

      <header className="topbar">
        <div className="brand">
          <b>Frontend Stage</b>
          <span className="brand-meta">Berlin · 2026</span>
        </div>
        <LocaleSwitcher locale={locale} />
      </header>

      <section className="hero">
        <p className="eyebrow">
          <span className="dot" aria-hidden="true" />
          {translateEyebrow()}
        </p>
        <h1>{translateHeadline()}</h1>
        <p className="greet">{translateGreeting(EVENT.attendeeName)}</p>
        <p className="lede">{translateLede()}</p>
      </section>

      <div className="grid">
        <TicketPanel locale={locale} />
        <ProofPanel locale={locale} />
      </div>

      <footer className="foot">
        <span className="foot-badge">Palamedes</span>
        {translateRenderedWith()}
        {" · "}
        {translateServerLocale()} <strong data-testid="server-locale-value">{localeLabel}</strong>
      </footer>

      <ClientReady />
    </main>
  ));
}

// examples/solid-route/src/routes/[locale].tsx
import { createMemo, Show } from "solid-js"
import { useParams } from "@solidjs/router"
import { t } from "@palamedes/core/macro"
import { Trans } from "@palamedes/solid/macro"
import { EVENT } from "@palamedes/example-ui"
import { ClientReady } from "../components/ClientReady"
import { LocaleSwitcher } from "../components/LocaleSwitcher"
import { ProofPanel } from "../components/ProofPanel"
import { SuggestionBanner } from "../components/SuggestionBanner"
import { TicketPanel } from "../components/TicketPanel"
import { loadRoutePageData } from "../lib/server"
import type { Locale } from "../lib/i18n"

type RoutePageData = {
  banner: {
    description: string
    recommendedLocale: Locale
    recommendedUrl: string
  } | null
  locale: Locale
  localeLabel: string
  renderedAt: string
}

function RoutePageContent(props: { data: RoutePageData }) {
  return (
    <main class="page-shell">
      <Show when={props.data.banner}>
        {(banner) => (
          <SuggestionBanner
            currentLocale={props.data.locale}
            description={banner().description}
            recommendedLocale={banner().recommendedLocale}
            recommendedUrl={banner().recommendedUrl}
          />
        )}
      </Show>

      <header class="topbar">
        <div class="brand">
          <b>Frontend Stage</b>
          <span class="brand-meta">Berlin · 2026</span>
        </div>
        <LocaleSwitcher locale={props.data.locale} />
      </header>

      <section class="hero">
        <p class="eyebrow">
          <span class="dot" aria-hidden="true" />
          <Trans>Localized for this document with Palamedes</Trans>
        </p>
        <h1>
          <Trans>Book your seat at Frontend Stage 2026</Trans>
        </h1>
        <p class="greet">{t`Welcome back, ${EVENT.attendeeName}.`}</p>
        <p class="lede">
          <Trans>
            Three days of talks on the craft of building for the web. Choose your tickets below.
          </Trans>
        </p>
      </section>

      <div class="grid">
        <TicketPanel locale={props.data.locale} />
        <ProofPanel locale={props.data.locale} />
      </div>

      <footer class="foot">
        <span class="foot-badge">Palamedes</span>
        <Trans>Rendered with Solid</Trans>
        {" · "}
        <Trans>server locale</Trans>{" "}
        <strong data-testid="server-locale-value">{props.data.localeLabel}</strong>
      </footer>

      <ClientReady />
    </main>
  )
}

export default function LocalePage() {
  const params = useParams<{ locale: string }>()
  const pageData = createMemo(() => loadRoutePageData(params.locale))

  return <Show when={pageData()}>{(page) => <RoutePageContent data={page()} />}</Show>
}
