// examples/tanstack-cookie/src/components/ProofPanel.tsx
import { useEffect, useState, useTransition } from "react"
import { plural } from "@palamedes/core/macro"
import { Trans as Fmt } from "@palamedes/react"
import { Trans } from "@palamedes/react/macro"
import { EVENT } from "@palamedes/example-ui"
import type { Locale } from "../lib/i18n"
import { getLocalizedServerStatus } from "../lib/server-functions"

type ProofPanelProps = {
  locale: Locale
}

export function ProofPanel({ locale }: ProofPanelProps) {
  const when = new Date(EVENT.startsAt)
  const seats = EVENT.seatsLeft
  const [message, setMessage] = useState<string | null>(null)
  const [isPending, startTransition] = useTransition()

  function refresh() {
    startTransition(async () => {
      const result = await getLocalizedServerStatus()
      setMessage(result.message)
    })
  }

  useEffect(() => {
    refresh()
  }, [locale])

  return (
    <aside className="aside">
      <div className="aside-head">
        <h3>
          <Trans>Behind the scenes</Trans>
        </h3>
        <span>
          <Trans>one switch, every format</Trans>
        </span>
      </div>

      <div className="feat">
        <div className="feat-row">
          <span className="feat-name">
            <Trans>Plural</Trans>
          </span>
          <span className="feat-out">
            {plural(seats, { one: "# seat left", other: "# seats left" })}
          </span>
        </div>
        <code>{`plural(seats, { one: "# seat left", other: "# seats left" })`}</code>
      </div>

      <div className="feat">
        <div className="feat-row">
          <span className="feat-name">
            <Trans>Currency</Trans>
          </span>
          <span className="feat-out">
            <Fmt
              message="{amount, number, ::currency/EUR}"
              values={{ amount: EVENT.ticketPrice }}
            />
          </span>
        </div>
        <code>{`{amount, number, ::currency/EUR}`}</code>
      </div>

      <div className="feat">
        <div className="feat-row">
          <span className="feat-name">
            <Trans>Number</Trans>
          </span>
          <span className="feat-out">
            <Fmt message="{count, number}" values={{ count: EVENT.attendeeCount }} />
          </span>
        </div>
        <code>{`{count, number}`}</code>
      </div>

      <div className="feat">
        <div className="feat-row">
          <span className="feat-name">
            <Trans>Date</Trans>
          </span>
          <span className="feat-out is-text">
            <Fmt message="{when, date, medium}" values={{ when }} />
          </span>
        </div>
        <code>{`{when, date, medium}`}</code>
      </div>

      <div className="feat">
        <div className="feat-row">
          <span className="feat-name">
            <Trans>Server</Trans>
          </span>
          <span className="feat-out is-text" data-testid="server-proof-message">
            {message ?? "…"}
          </span>
        </div>
        <button
          className="cta"
          data-testid="server-proof-trigger"
          disabled={isPending}
          onClick={refresh}
          type="button"
        >
          <Trans>Refresh server result</Trans>
        </button>
      </div>
    </aside>
  )
}

// examples/solid-cookie/src/components/ProofPanel.tsx
import { createEffect, createSignal } from "solid-js"
import { isServer } from "@solidjs/web"
import { plural } from "@palamedes/core/macro"
import { Trans as Fmt } from "@palamedes/solid"
import { Trans } from "@palamedes/solid/macro"
import { EVENT } from "@palamedes/example-ui"
import type { Locale } from "../lib/i18n"
import { getLocalizedServerStatus } from "../lib/server"

type ProofPanelProps = {
  locale: Locale
}

export function ProofPanel(props: ProofPanelProps) {
  const when = new Date(EVENT.startsAt)
  const seats = EVENT.seatsLeft
  const [message, setMessage] = createSignal<string | null>(null)
  const [isPending, setIsPending] = createSignal(false)

  async function refresh() {
    setIsPending(true)
    try {
      const result = await getLocalizedServerStatus()
      setMessage(result.message)
    } finally {
      setIsPending(false)
    }
  }

  createEffect(
    () => props.locale,
    () => {
      // Re-run whenever the locale changes so the server message stays in sync.
      if (!isServer) {
        void refresh()
      }
    }
  )

  return (
    <aside class="aside">
      <div class="aside-head">
        <h3>
          <Trans>Behind the scenes</Trans>
        </h3>
        <span>
          <Trans>one switch, every format</Trans>
        </span>
      </div>

      <div class="feat">
        <div class="feat-row">
          <span class="feat-name">
            <Trans>Plural</Trans>
          </span>
          <span class="feat-out">
            {plural(seats, { one: "# seat left", other: "# seats left" })}
          </span>
        </div>
        <code>{`plural(seats, { one: "# seat left", other: "# seats left" })`}</code>
      </div>

      <div class="feat">
        <div class="feat-row">
          <span class="feat-name">
            <Trans>Currency</Trans>
          </span>
          <span class="feat-out">
            <Fmt
              message="{amount, number, ::currency/EUR}"
              values={{ amount: EVENT.ticketPrice }}
            />
          </span>
        </div>
        <code>{`{amount, number, ::currency/EUR}`}</code>
      </div>

      <div class="feat">
        <div class="feat-row">
          <span class="feat-name">
            <Trans>Number</Trans>
          </span>
          <span class="feat-out">
            <Fmt message="{count, number}" values={{ count: EVENT.attendeeCount }} />
          </span>
        </div>
        <code>{`{count, number}`}</code>
      </div>

      <div class="feat">
        <div class="feat-row">
          <span class="feat-name">
            <Trans>Date</Trans>
          </span>
          <span class="feat-out is-text">
            <Fmt message="{when, date, medium}" values={{ when }} />
          </span>
        </div>
        <code>{`{when, date, medium}`}</code>
      </div>

      <div class="feat">
        <div class="feat-row">
          <span class="feat-name">
            <Trans>Server</Trans>
          </span>
          <span class="feat-out is-text" data-testid="server-proof-message">
            {message() ?? "…"}
          </span>
        </div>
        <button
          class="cta"
          data-testid="server-proof-trigger"
          disabled={isPending()}
          onClick={refresh}
          type="button"
        >
          <Trans>Refresh server result</Trans>
        </button>
      </div>
    </aside>
  )
}
