// examples/solid-tld/src/routes/index.tsx
import { createMemo, Show } from "solid-js";
import { t } from "@palamedes/core/macro";
import { Trans } from "@palamedes/solid/macro";
import { EVENT } from "@palamedes/example-ui";
import { ClientReady } from "../components/ClientReady";
import { LocaleSwitcher } from "../components/LocaleSwitcher";
import { ProofPanel } from "../components/ProofPanel";
import { SuggestionBanner } from "../components/SuggestionBanner";
import { TicketPanel } from "../components/TicketPanel";
import type { Locale } from "../lib/i18n";
import { loadHomePageData } from "../lib/server";

type HomePageData = {
  banner: {
    description: string;
    recommendedLocale: Locale;
    recommendedUrl: string;
  } | null;
  host: string | null;
  locale: Locale;
  localeLabel: string;
  renderedAt: string;
};

function HomePageContent(props: { data: HomePageData }) {
  return (
    <main class="page-shell">
      <Show when={props.data.banner}>
        {(banner) => (
          <SuggestionBanner
            currentLocale={props.data.locale}
            description={banner().description}
            recommendedLocale={banner().recommendedLocale}
            recommendedUrl={banner().recommendedUrl}
          />
        )}
      </Show>

      <header class="topbar">
        <div class="brand">
          <b>Frontend Stage</b>
          <span class="brand-meta">Berlin · 2026</span>
        </div>
        <LocaleSwitcher host={props.data.host} locale={props.data.locale} />
      </header>

      <section class="hero">
        <p class="eyebrow">
          <span class="dot" aria-hidden="true" />
          <Trans>Localized for this document with Palamedes</Trans>
        </p>
        <h1>
          <Trans>Book your seat at Frontend Stage 2026</Trans>
        </h1>
        <p class="greet">{t`Welcome back, ${EVENT.attendeeName}.`}</p>
        <p class="lede">
          <Trans>
            Three days of talks on the craft of building for the web. Choose your tickets below.
          </Trans>
        </p>
      </section>

      <div class="grid">
        <TicketPanel locale={props.data.locale} />
        <ProofPanel locale={props.data.locale} />
      </div>

      <footer class="foot">
        <span class="foot-badge">Palamedes</span>
        <Trans>Rendered with Solid</Trans>
        {" · "}
        <Trans>server locale</Trans>{" "}
        <strong data-testid="server-locale-value">{props.data.localeLabel}</strong>
      </footer>

      <ClientReady />
    </main>
  );
}

export default function HomePage() {
  const pageData = createMemo(() => loadHomePageData());

  return <Show when={pageData()}>{(page) => <HomePageContent data={page()} />}</Show>;
}

// examples/tanstack-cookie/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { t } from "@palamedes/core/macro";
import { Trans } from "@palamedes/react/macro";
import { EVENT } from "@palamedes/example-ui";
import { ClientReady } from "../components/ClientReady";
import { LocaleSwitcher } from "../components/LocaleSwitcher";
import { ProofPanel } from "../components/ProofPanel";
import { TicketPanel } from "../components/TicketPanel";
import { loadHomePageData } from "../lib/server-functions";

export const Route = createFileRoute("/")({
  loader: () => loadHomePageData(),
  component: Home,
});

function Home() {
  const { locale, localeLabel } = Route.useLoaderData();
  return (
    <main className="page-shell">
      <header className="topbar">
        <div className="brand">
          <b>Frontend Stage</b>
          <span className="brand-meta">Berlin · 2026</span>
        </div>
        <LocaleSwitcher locale={locale} />
      </header>

      <section className="hero">
        <p className="eyebrow">
          <span className="dot" aria-hidden="true" />
          <Trans>Localized for this document with Palamedes</Trans>
        </p>
        <h1>
          <Trans>Book your seat at Frontend Stage 2026</Trans>
        </h1>
        <p className="greet">{t`Welcome back, ${EVENT.attendeeName}.`}</p>
        <p className="lede">
          <Trans>
            Three days of talks on the craft of building for the web. Choose your tickets below.
          </Trans>
        </p>
      </section>

      <div className="grid">
        <TicketPanel locale={locale} />
        <ProofPanel locale={locale} />
      </div>

      <footer className="foot">
        <span className="foot-badge">Palamedes</span>
        <Trans>Rendered with TanStack Start</Trans>
        {" · "}
        <Trans>server locale</Trans>{" "}
        <strong data-testid="server-locale-value">{localeLabel}</strong>
      </footer>

      <ClientReady />
    </main>
  );
}
