// examples/solid-cookie/src/components/LazyCatalogPanel.tsx
import { Show, createErrorBoundary, createLoadingBoundary, createSignal, lazy } from "solid-js";

const LazyCatalogDetails = lazy(() => import("./LazyCatalogDetails"));

function LazyDetailsBoundary(): Element {
  return createErrorBoundary(
    () =>
      createLoadingBoundary(
        () => <LazyCatalogDetails />,
        () => <p>Loading details…</p>,
      ),
    () => (
      <p data-testid="lazy-catalog-error" role="alert">
        Details are temporarily unavailable. Reload the page to try again.
      </p>
    ),
  ) as unknown as Element;
}

export function LazyCatalogPanel() {
  const [open, setOpen] = createSignal(false);

  return (
    <section>
      <button onClick={() => setOpen((value) => !value)} type="button">
        Show lazy catalog details
      </button>
      <Show when={open()}>
        <LazyDetailsBoundary />
      </Show>
    </section>
  );
}

// examples/waku-cookie/src/components/LazyCatalogPanel.tsx
"use client";

import { Component, lazy, Suspense, useState, type ReactNode } from "react";

const LazyCatalogDetails = lazy(() => import("./LazyCatalogDetails"));

class LazyLoadErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  render() {
    if (this.state.error) {
      return (
        <p data-testid="lazy-catalog-error" role="alert">
          Details are temporarily unavailable. Reload the page to try again.
        </p>
      );
    }
    return this.props.children;
  }
}

export function LazyCatalogPanel() {
  const [open, setOpen] = useState(false);

  return (
    <section>
      <button onClick={() => setOpen((value) => !value)} type="button">
        Show lazy catalog details
      </button>
      {open ? (
        <LazyLoadErrorBoundary>
          <Suspense fallback={<p>Loading details…</p>}>
            <LazyCatalogDetails />
          </Suspense>
        </LazyLoadErrorBoundary>
      ) : null}
    </section>
  );
}
