// examples/solid-cookie/src/components/ClientReady.tsx
import { createSignal, onSettled, Show } from "solid-js"
import { isServer } from "@solidjs/web"
import { Trans } from "@palamedes/solid/macro"

export function ClientReady() {
  const [ready, setReady] = createSignal(false)

  onSettled(() => {
    if (!isServer) {
      setReady(true)
    }
  })

  return (
    <Show when={ready()}>
      <span data-testid="client-ready" hidden>
        ready
      </span>
      <span data-testid="client-locale-value" hidden>
        <Trans>Add to cart</Trans>
      </span>
    </Show>
  )
}

// examples/tanstack-cookie/src/components/ClientReady.tsx
import { useEffect, useState } from "react";
import { Trans } from "@palamedes/react/macro";

/** Renders a hidden marker once the app has hydrated, for browser verification. */
export function ClientReady() {
  const [ready, setReady] = useState(false);
  useEffect(() => setReady(true), []);
  if (!ready) {
    return null;
  }
  return (
    <>
      <span data-testid="client-ready" hidden />
      <span data-testid="client-locale-value" hidden>
        <Trans>Add to cart</Trans>
      </span>
    </>
  );
}
