// examples/waku-route/src/components/LocaleSwitcher.tsx
"use client";

import { buildLocaleSwitchItems } from "@palamedes/react";
import { Trans } from "@palamedes/react/macro";
import { LOCALES, LOCALE_LABELS, locales, type Locale } from "../lib/i18n";

type LocaleSwitcherProps = {
  locale: Locale;
};

export function LocaleSwitcher({ locale }: LocaleSwitcherProps) {
  const items = buildLocaleSwitchItems({
    locales: LOCALES,
    currentLocale: locale,
    labels: LOCALE_LABELS,
  });

  return (
    <div className="switcher">
      <span className="switcher-label">
        <Trans>Locale</Trans>
      </span>
      <div className="seg" role="group" aria-label="Language">
        {items.map((item) => (
          <a
            key={item.locale}
            data-testid={item.testId}
            aria-current={item.active ? "page" : undefined}
            href={`/${item.locale}`}
            onClick={() => {
              document.cookie = locales.serializeChoice(item.locale);
            }}
          >
            {item.locale.toUpperCase()}
          </a>
        ))}
      </div>
    </div>
  );
}

// examples/solidstart-route/src/components/LocaleSwitcher.tsx
import { For } from "solid-js"
import { buildLocaleSwitchItems } from "@palamedes/solid"
import { Trans } from "@palamedes/solid/macro"
import { LOCALES, LOCALE_LABELS, type Locale, locales } from "../lib/i18n"

type LocaleSwitcherProps = {
  locale: Locale
}

export function LocaleSwitcher(props: LocaleSwitcherProps) {
  const localeSwitchItems = () =>
    buildLocaleSwitchItems({
      locales: LOCALES,
      currentLocale: props.locale,
      labels: LOCALE_LABELS,
    })

  return (
    <div class="switcher">
      <span class="switcher-label">
        <Trans>Locale</Trans>
      </span>
      <div class="seg" role="group" aria-label="Language">
        <For each={localeSwitchItems()}>
          {(item) => (
            <a
              data-testid={item.testId}
              aria-current={item.active ? "page" : undefined}
              href={`/${item.locale}`}
              onClick={() => {
                document.cookie = locales.serializeChoice(item.locale)
              }}
            >
              {item.locale.toUpperCase()}
            </a>
          )}
        </For>
      </div>
    </div>
  )
}
