// examples/solid-subdomain/src/components/LocaleSwitcher.tsx
import { For } from "solid-js"
import { buildLocaleSwitchItems } from "@palamedes/solid"
import { Trans } from "@palamedes/solid/macro"
import { LOCALES, LOCALE_LABELS, type Locale, locales } from "../lib/i18n"

type LocaleSwitcherProps = {
  host: string | null
  locale: Locale
}

export function LocaleSwitcher(props: LocaleSwitcherProps) {
  const localeSwitchItems = () =>
    buildLocaleSwitchItems({
      locales: LOCALES,
      currentLocale: props.locale,
      labels: LOCALE_LABELS,
    })

  // Subdomain strategy: switching the locale means loading a different host, so
  // we build the target URL from the request host (the core control swaps the
  // locale label) and let the browser do a full document load. canonicalUrl
  // returns protocol-relative URLs, correct on http (local) and https (deployed).
  function hrefFor(target: Locale): string {
    return locales.canonicalUrl({ locale: target, pathname: "/", requestHost: props.host })
  }

  return (
    <div class="switcher">
      <span class="switcher-label">
        <Trans>Locale</Trans>
      </span>
      <div class="seg" role="group" aria-label="Language">
        <For each={localeSwitchItems()}>
          {(item) => (
            <a
              data-testid={item.testId}
              aria-current={item.active ? "page" : undefined}
              href={hrefFor(item.locale)}
              onClick={() => {
                document.cookie = locales.serializeChoice(item.locale)
              }}
            >
              {item.locale.toUpperCase()}
            </a>
          )}
        </For>
      </div>
    </div>
  )
}

// examples/waku-subdomain/src/components/LocaleSwitcher.tsx
"use client"

import { buildLocaleSwitchItems } from "@palamedes/react"
import { Trans } from "@palamedes/react/macro"
import { LOCALES, LOCALE_LABELS, locales, type Locale } from "../lib/i18n"

type LocaleSwitcherProps = {
  host: string | null
  locale: Locale
}

export function LocaleSwitcher({ host, locale }: LocaleSwitcherProps) {
  const items = buildLocaleSwitchItems({
    locales: LOCALES,
    currentLocale: locale,
    labels: LOCALE_LABELS,
  })

  // Subdomain strategy: switching the locale means loading a different host, so
  // we build the target URL from the request host (the core control swaps the
  // locale label) and let the browser do a full document load. canonicalUrl
  // returns protocol-relative URLs, correct on http (local) and https (deployed).
  function hrefFor(target: Locale): string {
    return locales.canonicalUrl({ locale: target, pathname: "/", requestHost: host })
  }

  return (
    <div className="switcher">
      <span className="switcher-label">
        <Trans>Locale</Trans>
      </span>
      <div className="seg" role="group" aria-label="Language">
        {items.map((item) => (
          <a
            key={item.locale}
            data-testid={item.testId}
            aria-current={item.active ? "page" : undefined}
            href={hrefFor(item.locale)}
            onClick={() => {
              document.cookie = locales.serializeChoice(item.locale)
            }}
          >
            {item.locale.toUpperCase()}
          </a>
        ))}
      </div>
    </div>
  )
}
