// examples/solidstart-cookie/src/routes/index.tsx
import { Show } from "solid-js"
import { createAsync } from "@solidjs/router"
import { t } from "@palamedes/core/macro"
import { Trans } from "@palamedes/solid/macro"
import { ClientReady } from "../components/ClientReady"
import { Counter } from "../components/Counter"
import { LocaleSwitcher } from "../components/LocaleSwitcher"
import { ServerQueryProbe } from "../components/ServerQueryProbe"
import { syncClientI18n } from "../lib/i18n"
import { loadHomePageData } from "../lib/server"

export default function HomePage() {
  const pageData = createAsync(() => loadHomePageData())

  return (
    <Show when={pageData()}>
      {(page) => {
        const data = page()
        syncClientI18n(data.locale)

        return (
          <main class="page-shell">
            <ClientReady />

            <section class="hero">
              <p class="kicker">SolidStart</p>
              <h1>{t`Palamedes in SolidStart with one runtime model.`}</h1>
              <p>
                <Trans>
                  This example proves a cookie-based locale flow in SolidStart with
                  SSR, first-request Accept-Language detection, cookie persistence,
                  .po imports, and localized server queries.
                </Trans>
              </p>
              <div class="button-row">
                <LocaleSwitcher locale={data.locale} />
              </div>
              <p class="footer-note">
                <Trans>Current locale:</Trans>{" "}
                <strong data-testid="server-locale-value">{data.localeLabel}</strong>
              </p>
            </section>

            <section class="grid cols-2">
              <section class="panel">
                <p class="kicker">
                  <Trans>Server-rendered proof</Trans>
                </p>
                <h2>
                  <Trans>SSR translation happens before the page reaches the browser.</Trans>
                </h2>
                <p class="muted">
                  {t`This panel was rendered on the server for locale ${data.localeLabel}.`}
                </p>
                <div class="stats">
                  <div>
                    <span class="eyebrow">
                      <Trans>Locale source</Trans>
                    </span>
                    <strong>{data.source}</strong>
                  </div>
                  <div>
                    <span class="eyebrow">
                      <Trans>Rendered on server</Trans>
                    </span>
                    <code>{data.renderedAt}</code>
                  </div>
                </div>
              </section>

              <Counter locale={data.locale} />
              <ServerQueryProbe locale={data.locale} />
            </section>
          </main>
        )
      }}
    </Show>
  )
}

// examples/tanstack-start/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router"
import { t } from "@palamedes/core/macro"
import { Trans } from "@palamedes/react/macro"
import { Counter } from "../components/Counter"
import { LocaleSwitcher } from "../components/LocaleSwitcher"
import { ServerFunctionProbe } from "../components/ServerFunctionProbe"
import { normalizeLocale, syncClientI18n } from "../lib/i18n"
import { loadHomePageData } from "../lib/server-functions"

type HomeSearch = {
  locale?: string
}

export const Route = createFileRoute("/")({
  validateSearch: (search: HomeSearch) => ({
    locale: normalizeLocale(search.locale),
  }),
  loaderDeps: ({ search }) => ({
    locale: search.locale,
  }),
  loader: ({ deps }) => loadHomePageData({ data: { locale: deps.locale } }),
  component: Home,
})

function Home() {
  const { locale, localeLabel, renderedAt } = Route.useLoaderData()
  syncClientI18n(locale)

  return (
    <main className="page-shell">
      <section className="hero">
        <p className="kicker">TanStack Start</p>
        <h1>{t`Palamedes without framework-specific runtime wrappers.`}</h1>
        <p>
          <Trans>
            This example proves the existing Vite-based Palamedes setup works in
            TanStack Start with SSR, locale switching, .po imports, and localized
            server functions.
          </Trans>
        </p>
        <div className="button-row">
          <LocaleSwitcher locale={locale} />
        </div>
        <p className="footer-note">
          <Trans>Current locale:</Trans> <strong>{localeLabel}</strong>
        </p>
      </section>

      <section className="grid cols-2">
        <section className="panel">
          <p className="kicker">
            <Trans>Server-rendered proof</Trans>
          </p>
          <h2>
            <Trans>SSR translation happens before the page reaches the browser.</Trans>
          </h2>
          <p className="muted">
            {t`This panel was rendered on the server for locale ${localeLabel}.`}
          </p>
          <div className="stats">
            <div>
              <span className="eyebrow">
                <Trans>Rendered on server</Trans>
              </span>
              <code>{renderedAt}</code>
            </div>
            <div>
              <span className="eyebrow">.po</span>
              <strong>
                <Trans>Loaded through the Palamedes Vite plugin</Trans>
              </strong>
            </div>
          </div>
        </section>

        <Counter locale={locale} />
        <ServerFunctionProbe locale={locale} />

        <section className="panel">
          <p className="kicker">
            <Trans>What this proves</Trans>
          </p>
          <h2>
            <Trans>No Lingui-owned runtime package is required here.</Trans>
          </h2>
          <ul className="muted">
            <li>
              <Trans>Macros come from @palamedes/core/macro and @palamedes/react/macro.</Trans>
            </li>
            <li>
              <Trans>SSR uses a request-local i18n instance via setServerI18nGetter().</Trans>
            </li>
            <li>
              <Trans>Client interactions reuse the same provider-free runtime model.</Trans>
            </li>
          </ul>
        </section>
      </section>
    </main>
  )
}
